<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ScheduleAssistant.Presentation</RootNamespace>
    <AssemblyName>ScheduleAssistant</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScheduleAssistant.Application\ScheduleAssistant.Application.csproj" />
    <ProjectReference Include="..\ScheduleAssistant.Infrastructure\ScheduleAssistant.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
