<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ScheduleAssistant.Spike002</RootNamespace>
    <AssemblyName>ScheduleAssistant.SPIKE002</AssemblyName>
  </PropertyGroup>
</Project>
